apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosy-infrastructure-loki-auth-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cosy
    server: https://kubernetes.default.svc
  source:
    path: kubernetes/infrastructure/loki/nginx-auth-proxy
    repoURL: https://github.com/Magenta-Mause/Cosy-Internal-Deployment
    targetRevision: main
  project: cosy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

